#!/bin/bash
docker build . -t formats
docker run -i --name toolformats formats:latest ./run_tools
docker cp toolformats:/flowstar/flowstar-2.1.0/outputs flowresults
docker cp toolformats:/juliareach/results juliaresults
docker cp toolformats:/GoTube-main/saved_outputs gotuberesults
