classdef kFCOut6Layer1327124 < nnet.layer.Layer & nnet.layer.Formattable
    %kFCOut6Layer1327124
    % Auto-generated by MATLAB on 07-Apr-2022 14:19:29
    
    
    properties
        % Non Trainable Parameters
        
    end
    
    properties (Learnable)
        % Trainable parameters
        FCOut6Kernel
    end
    
    properties (Hidden)
        % Code literals
        
    end
    
    methods
        function obj = kFCOut6Layer1327124(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
        end
        
        function varargout = predict(obj, inputs)
            [temp{1}] = FCOut6Layer1327124(inputs, obj.FCOut6Kernel, obj);
            
            % Extract results from function call.
            varargout{1} = temp{1}.value;
        end
    end
end

function [identity] = FCOut6Layer1327124(inputs, matmulReadvariableopResource, obj)
import mlp_nn.ops.*;
[inputs] = struct('value', inputs, 'rank', 2);

% % Unsupported operator: Sign
% output: steSign10Sign
% inputs: inputs
error('Unsupported TensorFlow operator.');
steSign10AddY.value = single(0.1);
steSign10AddY.rank = 0;
% Operation
[steSign10Add] = tfAdd(steSign10Sign, steSign10AddY);
% % Unsupported operator: Sign
% output: steSign10Sign1
% inputs: steSign10Add
error('Unsupported TensorFlow operator.');
steSign10Identity.value = steSign10Sign1.value;
steSign10Identity.rank = steSign10Sign1.rank;
[steSign10IdentityN{1}, steSign10IdentityN{2}] = tfIdentityN(steSign10Sign1, inputs);
steSign10IdentityN.rank = steSign10Sign1.rank;
MatMulReadVariableOp.value = matmulReadvariableopResource;
MatMulReadVariableOp.rank = 2;
% % Unsupported operator: Sign
% output: MatMulSteSign9Sign
% inputs: MatMulReadVariableOp
error('Unsupported TensorFlow operator.');
MatMulSteSign9AddY.value = single(0.1);
MatMulSteSign9AddY.rank = 0;
% Operation
[MatMulSteSign9Add] = tfAdd(MatMulSteSign9Sign, MatMulSteSign9AddY);
% % Unsupported operator: Sign
% output: MatMulSteSign9Sign1
% inputs: MatMulSteSign9Add
error('Unsupported TensorFlow operator.');
MatMulSteSign9Identity.value = MatMulSteSign9Sign1.value;
MatMulSteSign9Identity.rank = MatMulSteSign9Sign1.rank;
[MatMulSteSign9IdentityN{1}, MatMulSteSign9IdentityN{2}] = tfIdentityN(MatMulSteSign9Sign1, MatMulReadVariableOp);
MatMulSteSign9IdentityN.rank = MatMulSteSign9Sign1.rank;
% Mat Mul
[MatMul] = tfMatMul(steSign10IdentityN{1}, MatMulSteSign9IdentityN{1}, 0, 0);
Identity.value = MatMul.value;
Identity.rank = MatMul.rank;

% assigning outputs
identity = Identity;
end

