classdef kFCOut2Layer1326716 < nnet.layer.Layer & nnet.layer.Formattable
    %kFCOut2Layer1326716
    % Auto-generated by MATLAB on 07-Apr-2022 14:19:28
    
    
    properties
        % Non Trainable Parameters
        
    end
    
    properties (Learnable)
        % Trainable parameters
        FCOut2Kernel
    end
    
    properties (Hidden)
        % Code literals
        
    end
    
    methods
        function obj = kFCOut2Layer1326716(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
        end
        
        function varargout = predict(obj, inputs)
            [temp{1}] = FCOut2Layer1326716(inputs, obj.FCOut2Kernel, obj);
            
            % Extract results from function call.
            varargout{1} = temp{1}.value;
        end
    end
end

function [identity] = FCOut2Layer1326716(inputs, matmulReadvariableopResource, obj)
import mlp_nn.ops.*;
[inputs] = struct('value', inputs, 'rank', 2);

% % Unsupported operator: Sign
% output: steSign2Sign
% inputs: inputs
error('Unsupported TensorFlow operator.');
steSign2AddY.value = single(0.1);
steSign2AddY.rank = 0;
% Operation
[steSign2Add] = tfAdd(steSign2Sign, steSign2AddY);
% % Unsupported operator: Sign
% output: steSign2Sign1
% inputs: steSign2Add
error('Unsupported TensorFlow operator.');
steSign2Identity.value = steSign2Sign1.value;
steSign2Identity.rank = steSign2Sign1.rank;
[steSign2IdentityN{1}, steSign2IdentityN{2}] = tfIdentityN(steSign2Sign1, inputs);
steSign2IdentityN.rank = steSign2Sign1.rank;
MatMulReadVariableOp.value = matmulReadvariableopResource;
MatMulReadVariableOp.rank = 2;
% % Unsupported operator: Sign
% output: MatMulSteSign1Sign
% inputs: MatMulReadVariableOp
error('Unsupported TensorFlow operator.');
MatMulSteSign1AddY.value = single(0.1);
MatMulSteSign1AddY.rank = 0;
% Operation
[MatMulSteSign1Add] = tfAdd(MatMulSteSign1Sign, MatMulSteSign1AddY);
% % Unsupported operator: Sign
% output: MatMulSteSign1Sign1
% inputs: MatMulSteSign1Add
error('Unsupported TensorFlow operator.');
MatMulSteSign1Identity.value = MatMulSteSign1Sign1.value;
MatMulSteSign1Identity.rank = MatMulSteSign1Sign1.rank;
[MatMulSteSign1IdentityN{1}, MatMulSteSign1IdentityN{2}] = tfIdentityN(MatMulSteSign1Sign1, MatMulReadVariableOp);
MatMulSteSign1IdentityN.rank = MatMulSteSign1Sign1.rank;
% Mat Mul
[MatMul] = tfMatMul(steSign2IdentityN{1}, MatMulSteSign1IdentityN{1}, 0, 0);
Identity.value = MatMul.value;
Identity.rank = MatMul.rank;

% assigning outputs
identity = Identity;
end

