classdef kFCOut3Layer1326818 < nnet.layer.Layer & nnet.layer.Formattable
    %kFCOut3Layer1326818
    % Auto-generated by MATLAB on 07-Apr-2022 14:19:28
    
    
    properties
        % Non Trainable Parameters
        
    end
    
    properties (Learnable)
        % Trainable parameters
        FCOut3Kernel
    end
    
    properties (Hidden)
        % Code literals
        
    end
    
    methods
        function obj = kFCOut3Layer1326818(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
        end
        
        function varargout = predict(obj, inputs)
            [temp{1}] = FCOut3Layer1326818(inputs, obj.FCOut3Kernel, obj);
            
            % Extract results from function call.
            varargout{1} = temp{1}.value;
        end
    end
end

function [identity] = FCOut3Layer1326818(inputs, matmulReadvariableopResource, obj)
import mlp_nn.ops.*;
[inputs] = struct('value', inputs, 'rank', 2);

% % Unsupported operator: Sign
% output: steSign4Sign
% inputs: inputs
error('Unsupported TensorFlow operator.');
steSign4AddY.value = single(0.1);
steSign4AddY.rank = 0;
% Operation
[steSign4Add] = tfAdd(steSign4Sign, steSign4AddY);
% % Unsupported operator: Sign
% output: steSign4Sign1
% inputs: steSign4Add
error('Unsupported TensorFlow operator.');
steSign4Identity.value = steSign4Sign1.value;
steSign4Identity.rank = steSign4Sign1.rank;
[steSign4IdentityN{1}, steSign4IdentityN{2}] = tfIdentityN(steSign4Sign1, inputs);
steSign4IdentityN.rank = steSign4Sign1.rank;
MatMulReadVariableOp.value = matmulReadvariableopResource;
MatMulReadVariableOp.rank = 2;
% % Unsupported operator: Sign
% output: MatMulSteSign3Sign
% inputs: MatMulReadVariableOp
error('Unsupported TensorFlow operator.');
MatMulSteSign3AddY.value = single(0.1);
MatMulSteSign3AddY.rank = 0;
% Operation
[MatMulSteSign3Add] = tfAdd(MatMulSteSign3Sign, MatMulSteSign3AddY);
% % Unsupported operator: Sign
% output: MatMulSteSign3Sign1
% inputs: MatMulSteSign3Add
error('Unsupported TensorFlow operator.');
MatMulSteSign3Identity.value = MatMulSteSign3Sign1.value;
MatMulSteSign3Identity.rank = MatMulSteSign3Sign1.rank;
[MatMulSteSign3IdentityN{1}, MatMulSteSign3IdentityN{2}] = tfIdentityN(MatMulSteSign3Sign1, MatMulReadVariableOp);
MatMulSteSign3IdentityN.rank = MatMulSteSign3Sign1.rank;
% Mat Mul
[MatMul] = tfMatMul(steSign4IdentityN{1}, MatMulSteSign3IdentityN{1}, 0, 0);
Identity.value = MatMul.value;
Identity.rank = MatMul.rank;

% assigning outputs
identity = Identity;
end

