classdef kFCOut7Layer1327226 < nnet.layer.Layer & nnet.layer.Formattable
    %kFCOut7Layer1327226
    % Auto-generated by MATLAB on 07-Apr-2022 14:19:29
    
    
    properties
        % Non Trainable Parameters
        
    end
    
    properties (Learnable)
        % Trainable parameters
        FCOut7Kernel
    end
    
    properties (Hidden)
        % Code literals
        
    end
    
    methods
        function obj = kFCOut7Layer1327226(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
        end
        
        function varargout = predict(obj, inputs)
            [temp{1}] = FCOut7Layer1327226(inputs, obj.FCOut7Kernel, obj);
            
            % Extract results from function call.
            varargout{1} = temp{1}.value;
        end
    end
end

function [identity] = FCOut7Layer1327226(inputs, matmulReadvariableopResource, obj)
import mlp_nn.ops.*;
[inputs] = struct('value', inputs, 'rank', 2);

% % Unsupported operator: Sign
% output: steSign12Sign
% inputs: inputs
error('Unsupported TensorFlow operator.');
steSign12AddY.value = single(0.1);
steSign12AddY.rank = 0;
% Operation
[steSign12Add] = tfAdd(steSign12Sign, steSign12AddY);
% % Unsupported operator: Sign
% output: steSign12Sign1
% inputs: steSign12Add
error('Unsupported TensorFlow operator.');
steSign12Identity.value = steSign12Sign1.value;
steSign12Identity.rank = steSign12Sign1.rank;
[steSign12IdentityN{1}, steSign12IdentityN{2}] = tfIdentityN(steSign12Sign1, inputs);
steSign12IdentityN.rank = steSign12Sign1.rank;
MatMulReadVariableOp.value = matmulReadvariableopResource;
MatMulReadVariableOp.rank = 2;
% % Unsupported operator: Sign
% output: MatMulSteSign11Sign
% inputs: MatMulReadVariableOp
error('Unsupported TensorFlow operator.');
MatMulSteSign11AddY.value = single(0.1);
MatMulSteSign11AddY.rank = 0;
% Operation
[MatMulSteSign11Add] = tfAdd(MatMulSteSign11Sign, MatMulSteSign11AddY);
% % Unsupported operator: Sign
% output: MatMulSteSign11Sign1
% inputs: MatMulSteSign11Add
error('Unsupported TensorFlow operator.');
MatMulSteSign11Identity.value = MatMulSteSign11Sign1.value;
MatMulSteSign11Identity.rank = MatMulSteSign11Sign1.rank;
[MatMulSteSign11IdentityN{1}, MatMulSteSign11IdentityN{2}] = tfIdentityN(MatMulSteSign11Sign1, MatMulReadVariableOp);
MatMulSteSign11IdentityN.rank = MatMulSteSign11Sign1.rank;
% Mat Mul
[MatMul] = tfMatMul(steSign12IdentityN{1}, MatMulSteSign11IdentityN{1}, 0, 0);
Identity.value = MatMul.value;
Identity.rank = MatMul.rank;

% assigning outputs
identity = Identity;
end

