#!/usr/bin/env bash
set -ex

pwd

cd /root/capsule
pwd
ls -la

# add submodules (CORA, HyST, NNMT)
git submodule init

git submodule update

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
ls

cd /deps

ls

cd /deps/run_nnv_comparison

#chmod +x run_tools.sh
# run tool comparisons, this will take some time
./run_tools.sh > /results/run_nnv_comparison_log.txt 2>/results/run_nnv_comparison_err.txt

cd ~/

matlab -nodisplay -r "addpath(genpath('/deps')); addpath(genpath('/code')); startup_nnv; savepath; run_codeocean;"
