#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# set path to flowstar executable so relative directories not necessary
export PATH="/flowstar/flowstar-2.1.0/:$PATH"


pwd

# unfortunately, the git files do not exist when running the capsule, so this cannot be done to pull in the submodules
#cd /root/capsule
#pwd
#ls -la

# add submodules (CORA, HyST, NNMT)
#git submodule init
#git submodule update

cd /deps

cd /deps/run_nnv_comparison

chmod +x run_tools.sh
# run tool comparisons, this will take some time (~20-40 minutes or so, depends on codeocean load as this is run on shared resources)
#./run_tools.sh > /results/run_nnv_comparison_log.txt 2>/results/run_nnv_comparison_err.txt

#cd /results/logs
#pdflatex main.tex

ls /code

# ls /code/nnv/examples/Submission/FORMATS2022/Comparison/

# copy flowstar and juliareach scripts for formats'22 comparison
#cp -rf /code/nnv/examples/Submission/FORMATS2022/Comparison/flowstar/ /flowstar/flowstar-2.1.0/
#cp -rf /code/nnv/examples/Submission/FORMATS2022/Comparison/juliareach/ /juliareach
# may need to chmod some things

# cd /code/nnv/examples/Submission/FORMATS2022/Comparison
# chmod +x run_tools
# chmod +x run_tools_subset

echo "STARTING COMPARISONS"
# ./run_tools # Longer version, paper results (all benchmarks, table 3)
#echo "STARTING SUBSET"
# ./run_tools_subset # Default, faster (linear spiral and FPA, table 3)

# start up matlab and run
cd ~/

echo "STARTING MATLAB"

matlab -nodisplay -r "addpath(genpath('/deps')); addpath(genpath('/code')); startup_nnv; savepath; run_codeocean;"

#cd /results/logs/vgg
#pdflatex VGG16_Results.tex