function new_act = ActFunction(act)
%ACTFUNCTION It transforms the activation function list of the mat files
%generated by the nnmt tool and transforms it into matlab syntax
%   Detailed explanation goes here

act = strtrim(act);
% Remove empty white spaces and change name
if contains(act,'relu1')
    new_act = 'satlin';
elseif contains(act,'linear')
    new_act = 'purelin';
elseif contains(act,'relu2')
    new_act = 'satlins';
elseif contains(act,'relu')
    new_act = 'poslin';
elseif contains(act,'tanh')
    new_act = 'tansig';
elseif contains(act,'igmoid')
    new_act = 'logsig';
else
    new_act = act;
end
    
end

