#!/usr/bin/env bash
set -ex

ls /usr/local/

# mkdir deps && # already created in dockerfile
cd deps

wget -q https://www.dropbox.com/s/4p17xm4tlm8r9gs/sppFile.zip
mkdir -p /usr/local/MATLAB/R2022b/SupportPackages
unzip sppFile.zip -d /usr/local/MATLAB/R2022b/SupportPackages




cd /deps


#curl -LO https://tumcps.github.io/CORA/data/CORA_2018.zip
#unzip CORA_2018.zip && rm CORA_2018.zip

# handled via submodule for now, as there are some bugs fixed in our repository
#curl -LO https://tumcps.github.io/CORA/data/CORA_2020.zip
#unzip CORA_2020.zip && rm CORA_2020.zip

mkdir tbxmanager && cd tbxmanager

echo "
urlwrite('https://raw.githubusercontent.com/verivital/tbxmanager/master/tbxmanager.m', 'tbxmanager.m');
tbxmanager
tbxmanager install mpt mptdoc;
tbxmanager install lcp hysdel cddmex clpmex glpkmex fourier sedumi;
tbxmanager install yalmip; % todo: error due to license, need to force acceptance
cd /code/nnv;
startup_nnv; % adding dependencies and nnv to the path
" > install.m

pwd

ls

ls /usr/local/MATLAB
ls /usr
ls /usr/local
ls /
ls /deps

matlab -nodisplay -r "install; addpath(genpath('../../deps')); savepath"

matlab -nodisplay -r "addpath(genpath('/deps')); addpath(genpath('/code')); matlabshared.supportpkg.setSupportPackageRoot('/usr/local/MATLAB/R2022b');
addpath(genpath('/usr/local/MATLAB')); savepath;"
