#!/usr/bin/env bash
set -ex

mkdir deps && cd deps
YALMIP_RELEASE=R20171121

curl -sL https://github.com/yalmip/YALMIP/archive/$YALMIP_RELEASE.tar.gz | tar xz
mkdir tbxmanager_folder

matlab -nodisplay -r "fprintf('\nINSTALLING NNV....') \
  fprintf('\nIntalling tbxmanager (requires Matlab R2009a or later) ...'); \
  tbxmanager_folder = 'tbxmanager'; \
  list = dir; \
  cd(tbxmanager_folder); \
  urlwrite('https://raw.githubusercontent.com/verivital/tbxmanager/master/tbxmanager.m', 'tbxmanager.m'); \
  tbxmanager ;\
  fprintf('\nInstalling tbxmanager toolbox is done!'); \
  fprintf('\nIntalling mpt toolbox and other dependencies...\n'); \
  tbxmanager install mpt mptdoc; \
  tbxmanager install lcp hysdel cddmex clpmex glpkmex fourier sedumi; \
  fprintf('\nInstalling dependencies is done!'); \
  startup; \
  cd .. ; \
  addpath(genpath('deps')); savepath"
