center = [1; 1];
V = [1 0 1; 0 1 1];
P = ExamplePoly.randHrep('d',3);
S = Star([center V], P.A, P.b);
Z = S.getZono();
B = S.getOrientedBox();
figure;
Zono.plot(Z);
hold on;
Box.plot(B);
hold on;
Star.plot(S);