% toolbox_install.m -- ToolComparison AIVL setup.
%
% Extract the AI Verification Toolbox Support Package tarball into MATLAB's
% userpath, persist the addpath via startup.m so subsequent sessions pick
% it up automatically, and smoke-check that the AIVL entry points resolve
% (verifyNetworkRobustness, estimateNetworkOutputBounds).
%
% Searches the following locations for the tarball, in order:
%   $TOOLCOMPARISON_AIVL_TARBALL                (env var override)
%   /home/matlab/addons/atva26-aivl.tar.gz      (Docker stage path)
%   /data/aivl/atva26-aivl.tar.gz               (CodeOcean private data)
%   <toolcomparison>/scripts/atva26-aivl.tar.gz (if shipped alongside this script)
%
% Tarball recipe (run once on a workstation that has AIVL installed; from
% ~/Documents/MATLAB):
%
%   tar czf atva26-aivl.tar.gz \
%       SupportPackages/R*/toolbox/nnet/supportpackages/aivnv \
%       SupportPackages/R*/resources/aivnv \
%       SupportPackages/R*/appdata/components/softwaresupportpkgs/nnet/aivnv* \
%       SupportPackages/R*/appdata/files/softwaresupportpkgs/nnet/aivnv*
%
% After extraction, this script finds the aivnv toolbox dir wherever it
% landed (the tarball's source-release subdir is usually different from
% the running MATLAB release), so a tarball made on R2025b can extract
% cleanly into R2024a etc.

mlUser = userpath();
if isempty(mlUser)
    mlUser = fullfile(char(java.lang.System.getProperty('user.home')), 'Documents', 'MATLAB');
    if ~isfolder(mlUser), mkdir(mlUser); end
    userpath(mlUser);
end
release = string(version('-release'));     % e.g. "2025b"

candidates = string.empty;
envOverride = getenv('TOOLCOMPARISON_AIVL_TARBALL');
if ~isempty(envOverride),  candidates(end+1) = string(envOverride); end
candidates(end+1) = "/home/matlab/addons/atva26-aivl.tar.gz";
candidates(end+1) = "/data/aivl/atva26-aivl.tar.gz";
candidates(end+1) = string(fullfile(fileparts(mfilename('fullpath')), 'atva26-aivl.tar.gz'));

aivlTar = '';
for i = 1:numel(candidates)
    if exist(char(candidates(i)), 'file')
        aivlTar = char(candidates(i));
        break;
    end
end

fprintf('[toolbox_install] mlUser  = %s\n', mlUser);
fprintf('[toolbox_install] release = R%s\n', release);
if isempty(aivlTar)
    fprintf(2, '[toolbox_install] AIVL tarball not found in any of:\n');
    for i = 1:numel(candidates), fprintf(2, '  %s\n', candidates(i)); end
    fprintf(2, ['Skipping AIVL extraction. ToolComparison MW-side calls ', ...
                'will fail until a tarball is staged.\n']);
    return;
end

fprintf('[toolbox_install] tarball = %s\n', aivlTar);
fprintf('[toolbox_install] extracting -> %s\n', mlUser);
[st, out] = system(sprintf('tar -xzf %s -C %s', aivlTar, mlUser));
if st ~= 0
    fprintf(2, '[toolbox_install] tar failed (exit %d):\n%s\n', st, out);
    return;
end

% Find aivnv wherever it landed. The tarball may have been built from a
% different MATLAB release than the running one (e.g., packaged on R2025b
% but the MATLAB here is R2024a) -- in that case the extracted directory
% is SupportPackages/R2025b/... not R<current>/... Either is fine; AIVL's
% .m files are version-portable.
aivlMatches = dir(fullfile(char(mlUser), 'SupportPackages', 'R*', 'toolbox', 'nnet', 'supportpackages', 'aivnv'));
if isempty(aivlMatches)
    fprintf(2, '[toolbox_install] no aivnv directory found under %s/SupportPackages/R*/...\n', mlUser);
    return;
end
aivlDir = fullfile(aivlMatches(1).folder, aivlMatches(1).name);
fprintf('[toolbox_install] addpath %s  (isfolder=%d)\n', aivlDir, isfolder(aivlDir));
addpath(genpath(aivlDir));

% Persist via startup.m in userpath so subsequent sessions auto-load AIVL.
startupFile = fullfile(char(mlUser), 'startup.m');
fid = fopen(startupFile, 'w');
fprintf(fid, '%% Auto-generated by ToolComparison/scripts/toolbox_install.m on %s\n', char(datetime('now')));
fprintf(fid, 'addpath(genpath(''%s''));\n', aivlDir);
fclose(fid);
fprintf('[toolbox_install] wrote %s\n', startupFile);

rehash toolboxcache;

fprintf('\n[toolbox_install] smoke-checking AIVL entry points\n');
needAIVL = {'verifyNetworkRobustness', 'estimateNetworkOutputBounds'};
fail = false;
for i = 1:numel(needAIVL)
    p = which(needAIVL{i});
    if isempty(p)
        fprintf(2, '  MISSING: %s\n', needAIVL{i});
        fail = true;
    else
        fprintf('  OK: %s -> %s\n', needAIVL{i}, p);
    end
end
if fail
    fprintf(2, '[toolbox_install] AIVL entry points did not resolve after extract+addpath.\n');
    return;
end

fprintf('\n[toolbox_install] done.\n');
