function new_act = ActFunction(act)
%ACTFUNCTION It transforms the activation function list of the mat files
%generated by the nnmt tool and transforms it into matlab syntax
%   Detailed explanation goes here

act = strtrim(act);
% Remove empty white spaces and change name
if act == 'relu'
    new_act = 'ReLU';
elseif act == 'linear'
    new_act = 'Linear';
elseif act == 'relu1'
    new_act = 'SatLin';
elseif act == 'relu2'
    new_act = 'SatLins';
elseif act == 'tanh'
    new_act = 'TanSig';
elseif act == 'sigmoid'
    new_act = 'LogSig';   
end

end

