function new_act = ActFunction(act)
%ACTFUNCTION It transforms the activation function list of the mat files
%generated by the nnmt tool and transforms it into matlab syntax
%   Detailed explanation goes here

act = strtrim(act);
% Remove empty white spaces and change name
if contains(act,'relu1')
    new_act = 'SatLin';
elseif contains(act,'linear')
    new_act = 'Linear';
elseif contains(act,'relu2')
    new_act = 'SatLins';
elseif contains(act,'relu')
    new_act = 'ReLU';
elseif contains(act,'tanh')
    new_act = 'TanSig';
elseif contains(act,'igmoid')
    new_act = 'LogSig';   
end
    
end

