#!/bin/bash
mkdir /results/logs/
# Run juliareach
cd juliareach
julia startup.jl # disabled for now

pwd
ls

ls /code

ls /code/nnv/examples/Submission/FORMATS2022/Comparison/

ls ../

ls /

# Run Gotube
echo "STARTING GOTUBE"
cd /GoTube-main
#cd ../Gotube
pwd
ls
mkdir saved_outputs
./paper_submission_short.sh
# Run flowstar
#cd ../flowstar/flowstar-2.1.0/
pwd
ls
ls ../
#ls ../flowstar
pwd
#ls ../flowstar/flowstar/
#cd ../flowstar
echo "STARTING FLOWSTAR"
cd /code/nnv/examples/Submission/FORMATS2022/Comparison/flowstar/
pwd
ls
#cd ../flowstar/flowstar/
pwd
chmod +x run_short.sh
./run_short.sh
