#!/bin/bash
mkdir /results/logs/
# Run juliareach
cd juliareach

julia startup.jl # disabled for now, works but doesn't generate results in /results, need to copy or something
mv results /results/logs/juliaresults

pwd
ls

ls /code

ls /code/nnv/examples/Submission/FORMATS2022/Comparison/

ls ../

ls /

# Run Gotube
echo "STARTING GOTUBE"
cd /GoTube-main
#cd ../Gotube
pwd
ls
mkdir saved_outputs

./paper_submission_short.sh # works, uncomment for full run
mv /GoTube-main/saved_outputs /results/logs/tuberesults


# Run flowstar
ls /flowstar
cd /flowstar/flowstar-2.1.0/
pwd
ls
ls ../
#ls ../flowstar
pwd
#ls ../flowstar/flowstar/
#cd ../flowstar
echo "STARTING FLOWSTAR"

cp -rf /code/nnv/examples/Submission/FORMATS2022/Comparison/flowstar/* .

pwd
ls
#cd ../flowstar/flowstar/
pwd
chmod +x run_short.sh
./run_short.sh # for some reason doesn't return back to the calling shell script when done ?


echo "DONE FLOWSTAR"

exit 0
