#!/bin/bash
mkdir /results/logs/
# Run juliareach
cd juliareach
julia startup.jl
# Run Gotube
cd GoTube-main
mkdir saved_outputs
./paper_submission_comparion.sh
# Run flowstar
cd ../flowstar/flowstar-2.1.0/
./run_all.sh
