function Param = SetUpVCAS2AgentVerif

% Predefined Set Up for VCAS 2 Agent Verification model. Both agents use
% the same Plant and the same NN
% 
% 
% SETTINGS
%
% numagents: number of agents in the system
% plantDim: dimension of the state of the physical component of the system
% geometry: class with the method used to represent the set of states
% dynamics: plant dynamics
% method: reach method used by the neural network
% reachStep: time step for the analysis of the dynamics
% controlPeriod: execution period of the controllers
% outputMat: observer matrix
% NNfiles: directory of NN path files
% NNformat: class that defining correct format for NN
% NNreachMethod: class that contains only reachability analysis method
% commands: list of possible outputs
% pre: preprocessing func (splits interval if needed)
% norm: normalization function
% scale_mean: mean values of the inputs of the NNs (for normalization purpose)
% scale_range: range values of the inputs of the NNs (for normalization
% purpose)
% lambda: function applied on the output of the NNs, for deciding which
% command applying
% stopfcn: function that returns True if we reach the stopping criteria
% isSafefcn: function that returns True if we reach a safe scenario
% plotResults: function that plots the results of the reachability analysis

if ismac
    % Code to run on Mac platform
elseif isunix
    addpath('Models/VCAS/');
    addpath('Models/VCAS/nnv_format');
elseif ispc
    addpath('Models\VCAS\');
    addpath('Models\VCAS\nnv_format');
else
    disp('Platform not supported')
end

Param.numagents = 2;
Param.plantDim = 4;
Param.geometry = @Star;
Param.dynamics = @VCASVerifModel2Agent;
Param.method = 'approx-star';
Param.reachStep = 0.1;
Param.controlPeriod = 1;
Param.outputMat = eye(4);  % The observer --> selects the variables of interest
Param.NNfiles = {VCASVerifNeuralNetworks VCASVerifNeuralNetworks};
Param.NNformat = @FFNNS;
Param.NNreachMethod = @LayerS;
Param.commands = VCASCommands;
Param.pre = @VCASVerifPreProcessing;
Param.norm = @Normalize;
Param.scale_mean = {[0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                     0,0,0,20];
                     [0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                    0,0,0,20; ...
                     0,0,0,20]};
Param.scale_range = {[16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40];
                     [16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40; ...
                     16000,200,200,40]};
Param.lambda = {@ArgMaxVerif @ArgMaxVerif};
Param.stopfcn = @VCASVerifStoppingCriteria;
Param.isSafefcn = @VCASVerifSafetyness;
Param.plotResults = @VCASPlot;

end