classdef kFCOut4Layer1326920 < nnet.layer.Layer & nnet.layer.Formattable
    %kFCOut4Layer1326920
    % Auto-generated by MATLAB on 07-Apr-2022 14:19:28
    
    
    properties
        % Non Trainable Parameters
        
    end
    
    properties (Learnable)
        % Trainable parameters
        FCOut4Kernel
    end
    
    properties (Hidden)
        % Code literals
        
    end
    
    methods
        function obj = kFCOut4Layer1326920(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
        end
        
        function varargout = predict(obj, inputs)
            [temp{1}] = FCOut4Layer1326920(inputs, obj.FCOut4Kernel, obj);
            
            % Extract results from function call.
            varargout{1} = temp{1}.value;
        end
    end
end

function [identity] = FCOut4Layer1326920(inputs, matmulReadvariableopResource, obj)
import mlp_nn.ops.*;
[inputs] = struct('value', inputs, 'rank', 2);

% % Unsupported operator: Sign
% output: steSign6Sign
% inputs: inputs
error('Unsupported TensorFlow operator.');
steSign6AddY.value = single(0.1);
steSign6AddY.rank = 0;
% Operation
[steSign6Add] = tfAdd(steSign6Sign, steSign6AddY);
% % Unsupported operator: Sign
% output: steSign6Sign1
% inputs: steSign6Add
error('Unsupported TensorFlow operator.');
steSign6Identity.value = steSign6Sign1.value;
steSign6Identity.rank = steSign6Sign1.rank;
[steSign6IdentityN{1}, steSign6IdentityN{2}] = tfIdentityN(steSign6Sign1, inputs);
steSign6IdentityN.rank = steSign6Sign1.rank;
MatMulReadVariableOp.value = matmulReadvariableopResource;
MatMulReadVariableOp.rank = 2;
% % Unsupported operator: Sign
% output: MatMulSteSign5Sign
% inputs: MatMulReadVariableOp
error('Unsupported TensorFlow operator.');
MatMulSteSign5AddY.value = single(0.1);
MatMulSteSign5AddY.rank = 0;
% Operation
[MatMulSteSign5Add] = tfAdd(MatMulSteSign5Sign, MatMulSteSign5AddY);
% % Unsupported operator: Sign
% output: MatMulSteSign5Sign1
% inputs: MatMulSteSign5Add
error('Unsupported TensorFlow operator.');
MatMulSteSign5Identity.value = MatMulSteSign5Sign1.value;
MatMulSteSign5Identity.rank = MatMulSteSign5Sign1.rank;
[MatMulSteSign5IdentityN{1}, MatMulSteSign5IdentityN{2}] = tfIdentityN(MatMulSteSign5Sign1, MatMulReadVariableOp);
MatMulSteSign5IdentityN.rank = MatMulSteSign5Sign1.rank;
% Mat Mul
[MatMul] = tfMatMul(steSign6IdentityN{1}, MatMulSteSign5IdentityN{1}, 0, 0);
Identity.value = MatMul.value;
Identity.rank = MatMul.rank;

% assigning outputs
identity = Identity;
end

