classdef kFCOut1Layer1326614 < nnet.layer.Layer & nnet.layer.Formattable
    %kFCOut1Layer1326614
    % Auto-generated by MATLAB on 07-Apr-2022 14:19:27
    
    
    properties
        % Non Trainable Parameters
        
    end
    
    properties (Learnable)
        % Trainable parameters
        FCOut1Kernel
    end
    
    properties (Hidden)
        % Code literals
        
    end
    
    methods
        function obj = kFCOut1Layer1326614(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
        end
        
        function varargout = predict(obj, inputs)
            [temp{1}] = FCOut1Layer1326614(inputs, obj.FCOut1Kernel, obj);
            
            % Extract results from function call.
            varargout{1} = temp{1}.value;
        end
    end
end

function [identity] = FCOut1Layer1326614(inputs, matmulReadvariableopResource, obj)
import mlp_nn.ops.*;
[inputs] = struct('value', inputs, 'rank', 2);

MatMulReadVariableOp.value = matmulReadvariableopResource;
MatMulReadVariableOp.rank = 2;
% % Unsupported operator: Sign
% output: MatMulSteSignSign
% inputs: MatMulReadVariableOp
error('Unsupported TensorFlow operator.');
MatMulSteSignAddY.value = single(0.1);
MatMulSteSignAddY.rank = 0;
% Operation
[MatMulSteSignAdd] = tfAdd(MatMulSteSignSign, MatMulSteSignAddY);
% % Unsupported operator: Sign
% output: MatMulSteSignSign1
% inputs: MatMulSteSignAdd
error('Unsupported TensorFlow operator.');
MatMulSteSignIdentity.value = MatMulSteSignSign1.value;
MatMulSteSignIdentity.rank = MatMulSteSignSign1.rank;
[MatMulSteSignIdentityN{1}, MatMulSteSignIdentityN{2}] = tfIdentityN(MatMulSteSignSign1, MatMulReadVariableOp);
MatMulSteSignIdentityN.rank = MatMulSteSignSign1.rank;
% Mat Mul
[MatMul] = tfMatMul(inputs, MatMulSteSignIdentityN{1}, 0, 0);
Identity.value = MatMul.value;
Identity.rank = MatMul.rank;

% assigning outputs
identity = Identity;
end

